# Generated by Django 2.2 on 2020-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(default='', max_length=200)),
                ('price_sale', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
