# Generated by Django 2.2 on 2020-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
